import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import Header from './shared/components/Header'
import Footer from './shared/components/Footer'
import Mob_Header from './shared/components/Mob_header'
import Mobilefooter from './shared/components/Mobilefooter'
import FooterTop from '@/app/shared/components/FooterTop'
import { Suspense } from "react";

const inter = Work_Sans({
  subsets: ["latin"],
  weight: ['100', '300', '400', '500', '700'],
});

export const metadata: Metadata = {
  title: "One Global",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="overlays"></div>
        <div id="root"></div>
        <Suspense fallback={<div>Loading...</div>}>
        <div className="bg-white">
          <div className="md:hidden" >
            <Mob_Header />

          </div>
          <div className="hidden md:flex" >
            <Header />
          </div>
          {children}
          <FooterTop />
          <div className="md:hidden flex">
            <Mobilefooter />
          </div>
          <div className="hidden md:flex">
            <Footer />
          </div>
        </div>
        </Suspense>
      </body>
    </html>
  );
}

