import React from 'react'

const List = () => {
  return (
    <div className='container mx-auto text-[20px] px-6 md:px-0'>
      <h1 className='text-[25px] font-medium'>{`PRIVACY POLICY`}</h1>
      <p>{`One Global Hub for Business Accelerators Co. (“One Global Hub” or “Og Hub” or “we” or “us” or “our” or other similar pronouns) takes your privacy matters very seriously.`}</p>
      <p>{`Please read the following terms to learn more about our Privacy Policy ("Policy"). This Policy details how we receive, collect and use information in connection with our interface, or website or App / Site located at https://www.oghub.com (the "Site" “App / Site” “Interface”), the "Og Hub" App / Site and other products and services provided by "Og Hub" (all of the foregoing, collectively, the “Product” or the "Service" or the “Transactions” or the “Experiences”).`}</p>
      <p>{`By accessing to this App / SDK (An SDK or devkit is a Software Development Kit; a collection of software development tools in one installable package. This  facilitates the creation of ready to integrate solution,  compiler, debugger and perhaps a software framework, made available to contain all or every subscribed Service / Solution to be used by Business Clients, Service Providers, Integrators, Investors, regulators, any or All, with their specific use and purpose on a multichannel platform, application, protocols, technologies and respective operating system in combination of all) / Site or using the "Og Hub" Service, product, interface, App/Site, you are accepting the policies and practices described in this Policy, as such Policy may be amended from time to time. Each time you visit the Site or App / Site, or use the Service, you agree and expressly consent to our collection, use and disclosure of the information that you provide as described in this Policy.`}</p>
      <br/>
      <p>{`IF YOU ARE A USER ACCESSING THE SITE OR SERVICE FROM THE EUROPEAN UNION, ASIA, OR ANY OTHER REGION WITH LAWS OR REGULATIONS GOVERNING PERSONAL DATA COLLECTION, USE, AND DISCLOSURE THAT DIFFER FROM KUWAIT LAWS, PLEASE BE ADVISED THAT THROUGH YOUR CONTINUED USE OF THE SITE AND SERVICE, WHICH ARE GOVERNED BY KUWAIT LAW, THIS PRIVACY POLICY, AND OUR END USER LICENSE TERMS AND CONDITIONS, YOU MAY BE TRANSMITTING YOUR PERSONAL INFORMATION TO COUNTRIES (INCLUDING KUWAIT) WHERE LAWS REGARDING PROCESSING PERSONAL INFORMATION MAY BE LESS STRINGENT THAN THE PROCESSING OF PERSONAL INFORMATION IN YOUR COUNTRY AND YOU HEREBY CONSENT TO SUCH TRANSMISSION OF PERSONAL INFORMATION.`}</p>
      <h3 className='font-medium py-4 text-[22px]'>{`1. Collection and Use of Information`}</h3>
      <p>{`"Og Hub" Platform`}</p>
      <p>{`	When you install the "Og Hub" App / SDK / Site and register on the website, App, SDK, Interface and willing to interact with the provided Products and Services Via “Og Hub” Platform You will be asked to make Full “Know Your Customer (KYC)”  and providing us with your personal or Corporate information including but not a limited phone number, National ID, Passport, Driving License or Social Security, or Passport details or image identification, or Commercial License, or Commercial Registration certificate, or Corporate Article of Incorporation and which will be stored on our servers and will only be used to provide you with:`}</p>
      <ul className='list-disc pl-10'>
        <li>{`To resolve disputes`}</li>
        <li>{`Help promote safe services`}</li>
        <li>{`Measure consumer interest in our services`}</li>
        <li>{`Inform you about our products & services updates`}</li>
        <li>{`Customize your experience`}</li>
        <li>{`Detect & protect us against error, fraud and other criminal activity`}</li>
        <li>{`Enforce our terms and conditions, etc.`}</li>
      </ul>


      <p>{`We may use your contact information to send you recommend and personalize offers based on your previous orders and interests.`}</p>
      <p>{`"Og Hub" may interact with your phone's SMS inbox, placing incoming messages in your inbox or reading the contents of the activation SMS code sent to you by "Og Hub". WE WILL NOT ACCESS THE CONTENTS OF ANY OTHER SMS or contacts, for You nor Your Customers.`}</p>
      <h3 className='font-medium py-4 text-[22px]'>{`Cookies and Other Automatically Collected Data`}</h3>
      <p>{`If you have permitted your computer/device/phone to accept cookies, we may use cookies on the Site and App / Sitelication. Cookies are pieces of information that a website transfers to an individual's hard drive for record-keeping purposes. Cookies make web-surfing easier by saving preferences and browsing patterns while you are at the Site. No personal information will be collected via cookies and other tracking technology; however, if you previously provided personally identifiable information, cookies may be tied to such information. Aggregate cookie and tracking information may be shared with third parties. Our servers/App / Sites may automatically collect data about your Internet address when you visit the Site. This information, known as an Internet Protocol address, or IP Address, is a number that is automatically assigned to your computer by your Internet service provider whenever you are on the Internet. When you request pages from our Site/App / Site, our servers may log your IP Address and, if App / Sitelicable, your domain name. Your IP Address is used to help identify you and to gather demographic information about our members and users as a whole but does not include personally identifiable information. Our server may also record the referring page that linked you to us (e.g., another website or a search engine); the pages you visit on this Site; the website you visit after this Site; the ads you see and/or click on; other information about the type of Web browser, computer, platform, related software and settings you are using; any search terms you have entered on this Site or a referral site; and other Web usage activity and data logged by our servers. We use this information for internal system administration, to help diagnose problems with our servers, and to administer our Service. Such information may also be used to gather demographic information, such as country of origin and Internet Service Provider.`}</p>
      <h3>{`Third-Party Sites and Privacy Practices`}</h3>
      <p>{`You may arrive at our Site and/or download the "Og Hub" App / Site from another website. In addition, our Site/App / Site may contain links that will let you leave our Site and access another website. Websites linked to or from our Site/App / SDK / Site are not under the control of "Og Hub" and it is possible that these websites have a different privacy policy. Our Policy App / Sitelies solely to Personal Information that is acquired on the Site or through your use of our Service, and/or your relationship with "Og Hub". We urge you to be careful when you enter any Personal Information online. We accept no responsibility or liability for these other websites.`}</p>
      <h3 className='font-medium py-4 text-[22px]'>{`Analytics Collection`}</h3>
      <p>{`"Og Hub" uses Google Analytics, in house analytics to help us anonymously enhance, track usage and report user/visitor behavior information related to service and experience quality and users' standard log information to the Site and the "Og Hub" App / SDK /. This information (including but not limited to: IP address, data storage, maintenance services, metering data, database management, web/SDK analytics, Services usage, Account profile data, annual membership status and information processing) helps us analyze and evaluate how the "Og Hub" App / SDK / Site and Site are used as part of our ongoing efforts to improve the Site and "Og Hub" App / Site's features and services. No personally identifying data is included in this type of reporting. Google Analytics may have access to your information only for the purposes of performing these tasks and on behalf of "Og Hub" and under obligation similar in those in this Privacy Policy. For more information about the terms that govern Google Analytics, please visit the Google Analytics terms of service.`}</p>
      <p>{`We will never (and will not allow any third party to) use the statistical analytics tool unless You have to track or to collect any Personal Information of visitors or users. Google will not associate your IP address with any other data held by Google. Neither we nor Google will link, or seek to link, an IP address with the identity of a device user. We will not associate any data gathered from this site with any Personally Identifiable Information from any source unless you explicitly submit that information via a fill-in form on our website.`}</p>
      <h3 className='font-medium py-4 text-[22px]'>{`2. Sharing and Disclosure of Information`}</h3>
      <p>{`We do not rent, sell, or share any information about the user with any third parties, except as specifically described herein. We may disclose your Personal Information if we believe such action is necessary to:`}</p>
      <p>{`(a) Comply with the law, or legal process served on us;`}</p>
      <p>{`(b) Protect and defend our rights or property (including the enforcement of our Terms and Conditions); or`}</p>
      <p>{`(c) Act in urgent circumstances to protect the personal safety of users of our Service or members of the public.`}</p>

      <br />
      <p>{`To provide you with "Og Hub" services you have requested, "Og Hub" may sometimes, if necessary, share your Personal Information (excluding your address book and related information) and traffic data with trusted partner service providers and/or agents, for example: banking organizations or other providers of payment and analytical services, customer support, or hosting services. "Og Hub" will always require these third parties to take App / SDK / Appropriate organizational and technical measures to protect your personal data and traffic data and to observe the relevant legislation. "Og Hub" will never share your address book information with any third party, except as may be required by law (see below).
The following is a description of how we may share your Personal Information with trusted third-party partners. Should we add additional partners, we will immediately update this description:
`}</p>

      <p >{`1. We use third parties to process the payment and/or billing information that you submit on our Site or through the "Og Hub" App / SDK / Site to facilitate payment transactions. We require that these third parties take the Appropriate organizational and technical measures to protect your personal data and traffic data and to comply with relevant laws, but we are not liable or responsible for these third-party transactions. Therefore, you should review such third-party terms and conditions before providing your payment or billing information.`}</p>
      <p>{`We may disclose information about you if we determine that for national security, law enforcement, or other issues of public importance that disclosure of information is necessary.
We may from time to time ask you to provide information about your experiences which will be used to measure and improve quality. You are at no time under any obligation to provide any of such data. All information which is voluntarily submitted in feedback forms on the Site or any survey that you accept to take part in is used for the purposes of reviewing this feedback and improving the "Og Hub" software, products and websites.`}</p>


<p>{`We may contact you to send you messages about faults and service issues. Furthermore, we reserve the right to use email, the "Og Hub" software or SMS to notify you of any eventual claims related to your use of our software, websites and/or products, including without limitation claims of violation of third-party rights.`}</p>
<h3 className='font-medium py-4 text-[22px]'>{`2. Information Security`}</h3>
<p>{`We take reasonable precaution to protect Personal Information from misuse, loss and unauthorized access. Although we cannot guarantee that Personal Information will not be subject to unauthorized access, we have physical, electronic, and procedural safeguards in place to protect Personal Information. Personal Information is stored on our servers and protected by secured networks to which access is limited to a few authorized employees and personnel. However, no method of transmission over the Internet, or method of electronic storage, is 100% secure`}</p>
<h3 className='font-medium py-4 text-[22px]'>{`3. Business Transitions`}</h3>

<p>{`In the event that we go through a business transition, such as a merger, acquisition by another company, or sale of all or a portion of our assets, Personal Information will likely be among the assets transferred. As part of such a transaction the new entity will be required to commit to the same level of protection of your Personal Information as described in this Privacy Policy. If we cannot obtain such a commitment, we will not perform the business transition.
We will post a notice on this Site/App / SDK / Site of any such change in ownership or control of the Personal Information we may have prior to such transfer.`}
</p>
<h3>{`4. Changes to Policy`}</h3>
<p>{`From time to time, we may revise this Policy. We reserve the right to update or modify this Policy, or any other of our policies or practices, at any time with or without notice. However, we will not use your Personal Information in a way that is materially different than the uses described in this Policy without giving you an opportunity to opt-out of such differing uses. We will post the revised Policy on the Site, so that users can always be aware of what information we collect, how the information is used and under what circumstances such information may be disclosed. You agree to review the Policy periodically so that you are aware of any modifications. Your continued use of the Site indicates your assent to any changes and signifies your Terms and Conditions to the terms of our Policy. If you do not agree with these terms, you should not use the Site, the "Og Hub" App / Site, or any other Service.`}</p>
  <h3 className='font-medium py-4 text-[22px]'>{`5. Change or Removal of Information`}</h3> 
  <p>{`If you provided your e-mail address to us and wish to update it, you may do so by sending an e-mail to support@oghub.com `}</p> 
  <p>{`If you no longer wish to receive e-mail communication from us, such as offers, updates and newsletters, you may opt-out of receiving such communications by following the instructions included in each newsletter or communication. In addition, you can remove your e-mail address at any time by sending an e-mail with the subject line of UNSUBSCRIBE to support@oghub.com `}</p>
    <h3 className='font-medium py-4 text-[22px]'>{`6. Fees`}</h3>
    <p>{`By using "Og Hub" App / SDK / Site and/or by providing your information, you consent to the payment fees of the transaction during refund process to 3rd parties, banks and payment channels that been used inside "Og Hub" and you consent to get paid back with proof of the transaction and with remaining amount of the transaction after deduction of all fees...`}</p>
    <h3 className='font-medium py-4 text-[22px]'>{`7. Physical Verification`}</h3>
    
    <p>{`In case of customer is verified physically by One Global Hub employees in any of affiliate services or/and products, it will be considered as a general verification that can be used to purchase or subscribe or / and register on another affiliate services or/ and products of One Global Hub.”)`}</p>
   <h3 className='font-medium py-4 text-[22px]'>{`8. Contact Information`}</h3>
   <p className='font-medium'>{`Consent`}</p>
    <p>{`By using "Og Hub" Site/App, SDK and/or by providing your information, you consent to the collection and use of the information you disclose on "Og Hub" in accordance with this Privacy Policy, including but not limited to your consent for sharing your information as per this privacy policy.`}</p>
    <p className='font-medium'>{`Contact`}</p>
    <p className='pb-10'>{`Please direct all questions in connection with this Policy via e-mail to support@oghub.com or by writing to:
One Global Hub for Business Accelerators Co. L.L.C. at : Kuwait, Qibla, Fahad Al-Salem St., Jawharat Al Khaleej Commercial Building , 9th Floor, 
`}</p>
    </div>
  )
}

export default List
